-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 15:58:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_users` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `steam_account` VARCHAR(45) NULL,
  `telephone_number` VARCHAR(15) NOT NULL,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(10) NULL,
  `is_activated` SMALLINT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `steam_account_UNIQUE` (`steam_account` ASC) VISIBLE,
  UNIQUE INDEX `telephone_number_UNIQUE` (`telephone_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_currencies` (
  `currency_id` SMALLINT NOT NULL,
  `display_name` VARCHAR(45) NULL,
  `short_name` VARCHAR(3) NULL,
  PRIMARY KEY (`currency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_transactions` (
  `transaction_id` BIGINT NOT NULL,
  `user_id` INT NOT NULL,
  `transaction_type` VARCHAR(45) NULL,
  `value_from` DOUBLE NULL,
  `value_to` DOUBLE NULL,
  `currency_from` SMALLINT NULL,
  `currency_to` SMALLINT NULL,
  `order_id` BIGINT NULL,
  `insert_dt` DATETIME NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_transaction_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_transaction_currency_from_idx` (`currency_from` ASC) VISIBLE,
  INDEX `fk_transactioin_currency_to_idx` (`currency_to` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_currency_from`
    FOREIGN KEY (`currency_from`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactioin_currency_to`
    FOREIGN KEY (`currency_to`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_wallet` (
  `user_id` INT NOT NULL,
  `currency_id` SMALLINT NOT NULL,
  `amount` DOUBLE NULL,
  PRIMARY KEY (`user_id`, `currency_id`),
  INDEX `fk_wallet_currency_idx` (`currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_wallet_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wallet_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_exchange_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_exchange_rate` (
  `currency_from` SMALLINT NOT NULL,
  `currency_to` SMALLINT NOT NULL,
  `insert_dt` DATETIME NOT NULL,
  `exchange_rate` DOUBLE NOT NULL,
  PRIMARY KEY (`currency_from`, `currency_to`, `insert_dt`),
  INDEX `fk_exchange_rate_currency_to_idx` (`currency_to` ASC) VISIBLE,
  CONSTRAINT `fk_exchange_rate_currency_from`
    FOREIGN KEY (`currency_from`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exchange_rate_currency_to`
    FOREIGN KEY (`currency_to`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_orders` (
  `order_id` BIGINT NOT NULL,
  `user_id` INT NULL,
  `order_type` SMALLINT NULL,
  `currency_from` SMALLINT NULL,
  `currency_to` SMALLINT NULL,
  `amount` DOUBLE NULL,
  `price` DOUBLE NULL,
  `is_closed` SMALLINT NULL,
  `created_dt` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_orders_currency_idx` (`currency_from` ASC) VISIBLE,
  INDEX `fk_orders_currency_to_idx` (`currency_to` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_currency_from`
    FOREIGN KEY (`currency_from`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_currency_to`
    FOREIGN KEY (`currency_to`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_games` (
  `game_id` SMALLINT NOT NULL,
  `game_name` VARCHAR(45) NULL,
  `currency_id` SMALLINT NULL,
  PRIMARY KEY (`game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_proposals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_proposals` (
  `proposal_id` INT NOT NULL,
  `game_id` SMALLINT NULL,
  `display_name` VARCHAR(255) NULL,
  `proposal_text` VARCHAR(500) NULL,
  `currency_id` SMALLINT NULL,
  `price` DOUBLE NULL,
  `promocode` VARCHAR(45) NULL,
  `valid_from` DATETIME NULL,
  `valid_to` DATETIME NULL,
  PRIMARY KEY (`proposal_id`),
  INDEX `fk_proposals_game_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_proposals_currency_idx` (`currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_proposals_game`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`t_games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposals_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_currencies_has_t_currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_currencies_has_t_currencies` (
  `t_currencies_currency_id` SMALLINT NOT NULL,
  `t_currencies_currency_id1` SMALLINT NOT NULL,
  PRIMARY KEY (`t_currencies_currency_id`, `t_currencies_currency_id1`),
  INDEX `fk_t_currencies_has_t_currencies_t_currencies2_idx` (`t_currencies_currency_id1` ASC) VISIBLE,
  INDEX `fk_t_currencies_has_t_currencies_t_currencies1_idx` (`t_currencies_currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_currencies_has_t_currencies_t_currencies1`
    FOREIGN KEY (`t_currencies_currency_id`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_currencies_has_t_currencies_t_currencies2`
    FOREIGN KEY (`t_currencies_currency_id1`)
    REFERENCES `mydb`.`t_currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
