DELIMITER //
CREATE FUNCTION mydb.nextval(`seq_name` VARCHAR(255)) RETURNS INT UNSIGNED
    MODIFIES SQL DATA
    DETERMINISTIC
BEGIN
  UPDATE sequence SET id = LAST_INSERT_ID(id+1) WHERE name = seq_name;
  RETURN LAST_INSERT_ID();
END //

DELIMITER ;
